const constants = {
  CREATE_APPLICATION_REQUEST: 'application/CREATE_APPLICATION_REQUEST',
  CREATE_APPLICATION_SUCCESS: 'application/CREATE_APPLICATION_SUCCESS',
  CREATE_APPLICATION_FAILURE: 'application/CREATE_APPLICATION_FAILURE',
};

export default constants;
