const constants = {
  CHANGE_PAGE: 'application/CHANGE_PAGE',
  GET_APPLICATIONS_REQUEST_FAILURE: 'application/GET_APPLICATIONS_REQUEST_FAILURE',
  GET_APPLICATIONS_REQUEST_SUCCESS: 'application/GET_APPLICATIONS_REQUEST_SUCCESS',
  GET_APPLICATIONS_REQUEST: 'application/GET_APPLICATIONS_REQUEST',
  GET_APPLICATIONS_BY_PROJECT_ID_REQUEST: 'application/GET_APPLICATIONS_BY_PROJECT_ID_REQUEST',
  GET_APPLICATIONS_BY_PROJECT_ID_SUCCESS: 'application/GET_APPLICATIONS_BY_PROJECT_ID_SUCCESS',
  GET_APPLICATIONS_BY_PROJECT_ID_FAILURE: 'application/GET_APPLICATIONS_BY_PROJECT_ID_FAILURE',
  GET_APPLICATION_REQUEST: 'application/GET_APPLICATION_REQUEST',
  GET_APPLICATION_SUCCESS: 'application/GET_APPLICATION_SUCCESS',
  CREATE_APPLICATION_REQUEST: 'application/CREATE_APPLICATION_REQUEST',
  CREATE_APPLICATION_SUCCESS: 'application/CREATE_APPLICATION_SUCCESS',
  CREATE_APPLICATION_FAILURE: 'application/CREATE_APPLICATION_FAILURE',
};

export default constants;
