const constants = {
  GET_CICD_PROVIDERS_REQUEST: 'CICDProvider/GET_CICD_PROVIDERS_REQUEST',
  GET_CICD_PROVIDERS_SUCCESS: 'CICDProvider/GET_CICD_PROVIDERS_SUCCESS',
  GET_CICD_PROVIDERS_FAILURE: 'CICDProvider/GET_CICD_PROVIDERS_FAILURE',
};

export default constants;
