const constants = {
  GET_CLOUD_PROVIDERS_REQUEST: 'cloudProvider/GET_CLOUD_PROVIDERS_REQUEST',
  GET_CLOUD_PROVIDERS_SUCCESS: 'cloudProvider/GET_CLOUD_PROVIDERS_SUCCESS',
  GET_CLOUD_PROVIDERS_FAILURE: 'cloudProvider/GET_CLOUD_PROVIDERS_FAILURE',
};

export default constants;
