const constants = {
  GET_CODE_VERSION_MANAGER_PROVIDERS_REQUEST:
    'codeVersionManagerProvider/GET_CODE_VERSION_MANAGER_PROVIDERS_REQUEST',
  GET_CODE_VERSION_MANAGER_PROVIDERS_SUCCESS:
    'codeVersionManagerProvider/GET_CODE_VERSION_MANAGER_PROVIDERS_SUCCESS',
  GET_CODE_VERSION_MANAGER_PROVIDERS_FAILURE:
    'codeVersionManagerProvider/GET_CODE_VERSION_MANAGER_PROVIDERS_FAILURE',
};

export default constants;
