const constants = {
  GET_PROJECTS_REQUEST: 'project/GET_PROJECTS_REQUEST',
  GET_PROJECTS_SUCCESS: 'project/GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAILURE: 'project/GET_PROJECTS_FAILURE',
  GET_PROJECT_REQUEST: 'project/GET_PROJECT_REQUEST',
  GET_PROJECT_SUCCESS: 'project/GET_PROJECT_SUCCESS',
  GET_PROJECT_FAILURE: 'project/GET_PROJECT_FAILURE',
  CREATE_PROJECT_REQUEST: 'project/CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'project/CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'project/CREATE_PROJECT_FAILURE',
};

export default constants;
