const constants = {
  GET_PROJECTS_REQUEST: 'projects/GET_PROJECTS_REQUEST',
  CREATE_PROJECT_REQUEST: 'projects/CREATE_PROJECT_REQUEST',
  CREATE_PROJECT_SUCCESS: 'projects/CREATE_PROJECT_SUCCESS',
  CREATE_PROJECT_FAILURE: 'projects/CREATE_PROJECT_FAILURE',
};

export default constants;
