const constants = {
  GET_TEMPLATE_IMPLEMENTATIONS_REQUEST:
    'templateImplementation/GET_TEMPLATE_IMPLEMENTATIONS_REQUEST',
  GET_TEMPLATE_IMPLEMENTATIONS_SUCCESS:
    'templateImplementation/GET_TEMPLATE_IMPLEMENTATIONS_SUCCESS',
  GET_TEMPLATE_IMPLEMENTATIONS_FAILURE:
    'templateImplementation/GET_TEMPLATE_IMPLEMENTATIONS_FAILURE',
};

export default constants;
