const constants = {
  GET_TEMPLATES_REQUEST: 'template/GET_TEMPLATES_REQUEST',
  GET_TEMPLATES_SUCCESS: 'template/GET_TEMPLATES_SUCCESS',
  GET_TEMPLATES_FAILURE: 'template/GET_TEMPLATES_FAILURE',
};

export default constants;
